"""add_category_and_supplier_to_items

Revision ID: 17742a9dfdc4
Revises: dcff9a66aad6
Create Date: 2026-04-05 02:12:08.809877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17742a9dfdc4'
down_revision: Union[str, Sequence[str], None] = 'dcff9a66aad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_items_supplier_id', 'suppliers', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_supplier_id', type_='foreignkey')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
