"""add_price_adjustment_to_customers

Revision ID: 39a132a6266e
Revises: ae0e51aab30a
Create Date: 2026-04-12 21:37:48.328764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a132a6266e'
down_revision: Union[str, Sequence[str], None] = 'ae0e51aab30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_markup_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('price_markup_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_discount_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('price_discount_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('price_discount_value')
        batch_op.drop_column('price_discount_type')
        batch_op.drop_column('price_markup_value')
        batch_op.drop_column('price_markup_type')

    # ### end Alembic commands ###
