"""initial_schema

Revision ID: 3a55dc663cd5
Revises: 
Create Date: 2026-03-30 03:10:48.246720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a55dc663cd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=255), nullable=False),
    sa.Column('shop_address', sa.String(length=500), nullable=True),
    sa.Column('shop_phone', sa.String(length=50), nullable=True),
    sa.Column('shop_gstin', sa.String(length=50), nullable=True),
    sa.Column('default_tax_rate', sa.Float(), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('receiver_bank_name', sa.String(length=255), nullable=True),
    sa.Column('receiver_account_number', sa.String(length=50), nullable=True),
    sa.Column('receiver_ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_profiles_id'), ['id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('gstin', sa.String(length=50), nullable=True),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone_number'), ['phone_number'], unique=False)

    op.create_table('invoice_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_sequences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_sequences_year'), ['year'], unique=True)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('selling_price_retail', sa.Float(), nullable=False),
    sa.Column('selling_price_wholesale', sa.Float(), nullable=False),
    sa.Column('current_stock_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_of_measurement', sa.String(length=20), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('enable_low_stock_alert', sa.Boolean(), nullable=False),
    sa.Column('has_variants', sa.Boolean(), nullable=False),
    sa.Column('variant_type', sa.String(length=50), nullable=True),
    sa.Column('hsn_sac_code', sa.String(length=30), nullable=True),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_brand_name'), ['brand_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_item_name'), ['item_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_sku'), ['sku'], unique=True)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('gstin', sa.String(length=50), nullable=True),
    sa.Column('supplier_bank_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('supplier_bank_ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_phone_number'), ['phone_number'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('sub_total', sa.Float(), nullable=True),
    sa.Column('total_tax_amount', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIALLY_PAID', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)

    op.create_table('item_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('variant_value', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_variants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_variants_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_variants_sku'), ['sku'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('credit_balance', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)

    op.create_table('stock_audits',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('delta_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_audits_id'), ['id'], unique=False)

    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('gst_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_items_id'), ['id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_id'), ['id'], unique=False)

    op.create_table('return_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('total_credit', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('total_items_in_invoice', sa.Integer(), nullable=False),
    sa.Column('items_returned_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_receipts_id'), ['id'], unique=False)

    op.create_table('return_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_receipt_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_returned', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reason_category', sa.Enum('DAMAGED', 'UNABLE_TO_PAY', 'UNABLE_TO_SELL', 'BETTER_DEAL', 'QUALITY_ISSUE', 'WRONG_ITEM', 'OTHER', name='returnreasoncategory'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['return_receipt_id'], ['return_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_line_items_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_line_items_id'))

    op.drop_table('return_line_items')
    with op.batch_alter_table('return_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_receipts_id'))

    op.drop_table('return_receipts')
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_id'))

    op.drop_table('invoice_line_items')
    with op.batch_alter_table('stock_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_audits_id'))

    op.drop_table('stock_audits')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('item_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_variants_sku'))
        batch_op.drop_index(batch_op.f('ix_item_variants_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_variants_id'))

    op.drop_table('item_variants')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_phone_number'))
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_sku'))
        batch_op.drop_index(batch_op.f('ix_items_item_name'))
        batch_op.drop_index(batch_op.f('ix_items_id'))
        batch_op.drop_index(batch_op.f('ix_items_brand_name'))

    op.drop_table('items')
    with op.batch_alter_table('invoice_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_sequences_year'))
        batch_op.drop_index(batch_op.f('ix_invoice_sequences_id'))

    op.drop_table('invoice_sequences')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone_number'))
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))

    op.drop_table('customers')
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_profiles_id'))

    op.drop_table('company_profiles')
    # ### end Alembic commands ###
