"""add_default_credit_days_to_company_profile

Revision ID: ae0e51aab30a
Revises: 17742a9dfdc4
Create Date: 2026-04-12 21:17:26.894577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0e51aab30a'
down_revision: Union[str, Sequence[str], None] = '17742a9dfdc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_credit_days', sa.Integer(), server_default='60', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.drop_column('default_credit_days')

    # ### end Alembic commands ###
