from fastapi import APIRouter, Depends, Query, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import func, case
from typing import List, Optional, Any, Dict
from datetime import datetime, date as date_type, timedelta
from pydantic import BaseModel
from app.db.session import get_db
from app.models.customer import CustomerModel
from app.models.invoice import InvoiceModel, InvoiceLineItemModel, PaymentStatus
from app.models.item import ItemModel
from app.models.payment import PaymentModel

router = APIRouter()


class AgingBucket(BaseModel):
  customer_id: int
  customer_name: str
  customer_type: str
  current: float        # not yet due (no due_date, or due_date >= today)
  days_1_30: float
  days_31_60: float
  days_61_90: float
  days_over_90: float
  total_outstanding: float


class AgingReportResponse(BaseModel):
  rows: List[AgingBucket]
  totals: AgingBucket


@router.get(
    "/aging/",
    response_model=AgingReportResponse,
    summary="AR aging report",
    description=(
        "Accounts receivable aging — groups all outstanding invoices per customer into buckets:\n\n"
        "| Bucket | Criteria |\n"
        "|---|---|\n"
        "| **Current** | No due date, or due date ≥ today |\n"
        "| **1–30 days** | Overdue by 1–30 days |\n"
        "| **31–60 days** | Overdue by 31–60 days |\n"
        "| **61–90 days** | Overdue by 61–90 days |\n"
        "| **90+ days** | Overdue by more than 90 days |\n\n"
        "Walk-in Customer is always excluded. Results include a `totals` row summing all customers."
    ),
)
def get_aging_report(
  customer_type: Optional[str] = None,
  db: Session = Depends(get_db)
):
  today = datetime.utcnow().date()

  invoices = (
    db.query(InvoiceModel)
    .join(CustomerModel, InvoiceModel.customer_id == CustomerModel.id)
    .filter(
      InvoiceModel.payment_status != PaymentStatus.PAID,
      CustomerModel.name != 'Walk-in Customer',
    )
  )

  if customer_type:
    invoices = invoices.filter(CustomerModel.customer_type == customer_type)

  invoices = invoices.all()

  # Aggregate per customer
  buckets: dict[int, AgingBucket] = {}

  for inv in invoices:
    cid = inv.customer_id
    if cid not in buckets:
      buckets[cid] = AgingBucket(
        customer_id=cid,
        customer_name=inv.customer.name,
        customer_type=inv.customer.customer_type,
        current=0.0,
        days_1_30=0.0,
        days_31_60=0.0,
        days_61_90=0.0,
        days_over_90=0.0,
        total_outstanding=0.0,
      )

    unpaid = float(inv.grand_total - inv.amount_paid)
    bucket = buckets[cid]

    if inv.due_date is None:
      bucket.current += unpaid
    else:
      due = inv.due_date.date() if hasattr(inv.due_date, 'date') else inv.due_date
      days_past = (today - due).days
      if days_past <= 0:
        bucket.current += unpaid
      elif days_past <= 30:
        bucket.days_1_30 += unpaid
      elif days_past <= 60:
        bucket.days_31_60 += unpaid
      elif days_past <= 90:
        bucket.days_61_90 += unpaid
      else:
        bucket.days_over_90 += unpaid

    bucket.total_outstanding += unpaid

  rows = sorted(buckets.values(), key=lambda r: r.total_outstanding, reverse=True)

  totals = AgingBucket(
    customer_id=0,
    customer_name="TOTAL",
    customer_type="",
    current=sum(r.current for r in rows),
    days_1_30=sum(r.days_1_30 for r in rows),
    days_31_60=sum(r.days_31_60 for r in rows),
    days_61_90=sum(r.days_61_90 for r in rows),
    days_over_90=sum(r.days_over_90 for r in rows),
    total_outstanding=sum(r.total_outstanding for r in rows),
  )

  return AgingReportResponse(rows=rows, totals=totals)


# ── Daily Sales Summary ───────────────────────────────────────────────────────

class SalesByMethod(BaseModel):
  method: str
  count: int
  total: float

class SalesByType(BaseModel):
  customer_type: str
  count: int
  total: float

class DailySummaryResponse(BaseModel):
  date: str
  invoice_count: int
  total_sales: float
  by_customer_type: List[SalesByType]
  payment_count: int
  total_collected: float
  by_payment_method: List[SalesByMethod]


@router.get(
    "/daily-summary/",
    response_model=DailySummaryResponse,
    summary="Daily sales summary",
    description=(
        "Returns invoice and payment totals for a single calendar day.\n\n"
        "- Invoices are broken down by customer type (Retail / Wholesale).\n"
        "- Payments are broken down by payment method.\n"
        "- `credit_note` payments (generated by returns) are excluded from the payment totals.\n"
        "- Defaults to today (UTC) when `date` is not provided."
    ),
    responses={400: {"description": "Invalid date format — use YYYY-MM-DD"}},
)
def get_daily_summary(
  date: Optional[str] = Query(None, description="Date in YYYY-MM-DD format (default: today)"),
  db: Session = Depends(get_db)
):
  if date:
    try:
      target = datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
      raise HTTPException(status_code=400, detail="Invalid date format. Use YYYY-MM-DD")
  else:
    target = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)

  day_start = target.replace(hour=0, minute=0, second=0, microsecond=0)
  day_end = target.replace(hour=23, minute=59, second=59, microsecond=999999)

  # ── Invoices created on this day ───────────────────────────────────────────
  invoice_rows = (
    db.query(
      CustomerModel.customer_type,
      func.count(InvoiceModel.id).label('count'),
      func.coalesce(func.sum(InvoiceModel.grand_total), 0).label('total'),
    )
    .join(CustomerModel, InvoiceModel.customer_id == CustomerModel.id)
    .filter(InvoiceModel.invoice_date >= day_start, InvoiceModel.invoice_date <= day_end)
    .group_by(CustomerModel.customer_type)
    .all()
  )

  total_sales = sum(float(r.total) for r in invoice_rows)
  invoice_count = sum(r.count for r in invoice_rows)
  by_customer_type = [
    SalesByType(customer_type=r.customer_type or 'Unknown', count=r.count, total=float(r.total))
    for r in invoice_rows
  ]

  # ── Payments received on this day (exclude credit_note) ───────────────────
  payment_rows = (
    db.query(
      PaymentModel.payment_method,
      func.count(PaymentModel.id).label('count'),
      func.coalesce(func.sum(PaymentModel.amount), 0).label('total'),
    )
    .filter(
      PaymentModel.date >= day_start,
      PaymentModel.date <= day_end,
      PaymentModel.payment_method != 'credit_note',
    )
    .group_by(PaymentModel.payment_method)
    .all()
  )

  total_collected = sum(float(r.total) for r in payment_rows)
  payment_count = sum(r.count for r in payment_rows)
  by_payment_method = [
    SalesByMethod(method=r.payment_method or 'unspecified', count=r.count, total=float(r.total))
    for r in payment_rows
  ]

  return DailySummaryResponse(
    date=target.strftime("%Y-%m-%d"),
    invoice_count=invoice_count,
    total_sales=total_sales,
    by_customer_type=by_customer_type,
    payment_count=payment_count,
    total_collected=total_collected,
    by_payment_method=by_payment_method,
  )


# ── Revenue Analytics ─────────────────────────────────────────────────────────

class MonthlyRevenue(BaseModel):
  month: str          # "2026-01"
  month_label: str    # "Jan 2026"
  retail: float
  wholesale: float
  total: float
  invoice_count: int

class TopCustomer(BaseModel):
  customer_id: int
  customer_name: str
  customer_type: str
  total: float
  invoice_count: int

class RevenueSummary(BaseModel):
  retail_total: float
  wholesale_total: float
  grand_total: float
  retail_pct: float
  wholesale_pct: float
  invoice_count: int

class RevenueReportResponse(BaseModel):
  months: List[MonthlyRevenue]
  top_customers: List[TopCustomer]
  summary: RevenueSummary
  period_months: int


_MONTH_NAMES = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']


@router.get(
    "/revenue/",
    response_model=RevenueReportResponse,
    summary="Revenue analytics — monthly trend + top customers",
    description=(
        "Returns monthly revenue split by Retail vs Wholesale, top 10 customers by revenue, and period summary totals.\n\n"
        "- Months with zero invoices are included in the series (filled with zeros) so the chart stays continuous.\n"
        "- `summary` includes `retail_pct` and `wholesale_pct` for the pie chart.\n"
        "- Lookback window: `months` param (1–36, default 12)."
    ),
)
def get_revenue_report(
  months: int = Query(12, ge=1, le=36, description="Number of months to include (max 36)"),
  db: Session = Depends(get_db),
):
  today = datetime.utcnow().date()

  # Compute the first day of the window (start of month, N months ago)
  first_day = today.replace(day=1)
  for _ in range(months - 1):
    first_day = (first_day - timedelta(days=1)).replace(day=1)

  cutoff = datetime(first_day.year, first_day.month, 1)

  # ── Monthly revenue by customer type ────────────────────────────────────────
  rows = (
    db.query(
      func.strftime('%Y-%m', InvoiceModel.invoice_date).label('month'),
      CustomerModel.customer_type,
      func.coalesce(func.sum(InvoiceModel.grand_total), 0).label('total'),
      func.count(InvoiceModel.id).label('count'),
    )
    .join(CustomerModel, InvoiceModel.customer_id == CustomerModel.id)
    .filter(InvoiceModel.invoice_date >= cutoff)
    .group_by('month', CustomerModel.customer_type)
    .order_by('month')
    .all()
  )

  # Aggregate into {month_key: {retail, wholesale, count}} map
  monthly_map: dict = {}
  for row in rows:
    m = row.month
    if m not in monthly_map:
      monthly_map[m] = {'retail': 0.0, 'wholesale': 0.0, 'count': 0}
    ct = (row.customer_type or '').lower()
    if 'retail' in ct:
      monthly_map[m]['retail'] += float(row.total)
    else:
      monthly_map[m]['wholesale'] += float(row.total)
    monthly_map[m]['count'] += row.count

  # Build complete month list (fill in zeros for months with no invoices)
  month_list: List[MonthlyRevenue] = []
  cur = first_day
  for _ in range(months):
    key = cur.strftime('%Y-%m')
    data = monthly_map.get(key, {'retail': 0.0, 'wholesale': 0.0, 'count': 0})
    label = f"{_MONTH_NAMES[cur.month - 1]} {cur.year}"
    month_list.append(MonthlyRevenue(
      month=key,
      month_label=label,
      retail=data['retail'],
      wholesale=data['wholesale'],
      total=data['retail'] + data['wholesale'],
      invoice_count=data['count'],
    ))
    # Advance to next month
    if cur.month == 12:
      cur = cur.replace(year=cur.year + 1, month=1)
    else:
      cur = cur.replace(month=cur.month + 1)

  # ── Top customers by revenue in the period ──────────────────────────────────
  top_rows = (
    db.query(
      CustomerModel.id,
      CustomerModel.name,
      CustomerModel.customer_type,
      func.coalesce(func.sum(InvoiceModel.grand_total), 0).label('total'),
      func.count(InvoiceModel.id).label('count'),
    )
    .join(InvoiceModel, InvoiceModel.customer_id == CustomerModel.id)
    .filter(InvoiceModel.invoice_date >= cutoff)
    .group_by(CustomerModel.id, CustomerModel.name, CustomerModel.customer_type)
    .order_by(func.sum(InvoiceModel.grand_total).desc())
    .limit(10)
    .all()
  )

  top_customers = [
    TopCustomer(
      customer_id=r.id,
      customer_name=r.name,
      customer_type=r.customer_type or 'Unknown',
      total=float(r.total),
      invoice_count=r.count,
    )
    for r in top_rows
  ]

  # ── Summary totals ───────────────────────────────────────────────────────────
  retail_total = sum(m.retail for m in month_list)
  wholesale_total = sum(m.wholesale for m in month_list)
  grand_total = retail_total + wholesale_total

  summary = RevenueSummary(
    retail_total=retail_total,
    wholesale_total=wholesale_total,
    grand_total=grand_total,
    retail_pct=round(retail_total / grand_total * 100, 1) if grand_total > 0 else 0.0,
    wholesale_pct=round(wholesale_total / grand_total * 100, 1) if grand_total > 0 else 0.0,
    invoice_count=sum(m.invoice_count for m in month_list),
  )

  return RevenueReportResponse(
    months=month_list,
    top_customers=top_customers,
    summary=summary,
    period_months=months,
  )


# ── Inventory Value Report ────────────────────────────────────────────────────

@router.get(
    "/inventory-value/",
    summary="Inventory value / stock intelligence",
    description=(
        "Full stock statement with value, movement, and health metrics.\n\n"
        "**Returns:**\n"
        "- `summary`: totals at cost and retail, count by status (in_stock / low_stock / out_of_stock / dead_stock), health %\n"
        "- `items`: per-item detail including `units_sold_30d` (velocity), `stock_status`, and both cost/retail values\n"
        "- `by_category`: value grouped by category (sorted by cost value)\n"
        "- `by_brand`: top 15 brands by cost value\n\n"
        "**Dead stock** = items with stock > 0 and zero units sold in the last 30 days.\n"
        "Only active items (`is_active=true`) are included."
    ),
)
def get_inventory_value(db: Session = Depends(get_db)):
  today = datetime.utcnow()
  cutoff_30d = today - timedelta(days=30)

  # Subquery: units sold per item in last 30 days
  sold_sq = (
    db.query(
      InvoiceLineItemModel.item_id,
      func.coalesce(func.sum(InvoiceLineItemModel.quantity), 0).label('units_sold_30d'),
    )
    .join(InvoiceModel, InvoiceLineItemModel.invoice_id == InvoiceModel.id)
    .filter(InvoiceModel.invoice_date >= cutoff_30d)
    .group_by(InvoiceLineItemModel.item_id)
    .subquery()
  )

  rows = (
    db.query(ItemModel, func.coalesce(sold_sq.c.units_sold_30d, 0).label('units_sold_30d'))
    .outerjoin(sold_sq, ItemModel.id == sold_sq.c.item_id)
    .filter(ItemModel.is_active == True)
    .all()
  )

  items_out = []
  for item, units_sold_30d in rows:
    stock = item.current_stock_quantity or 0
    threshold = item.low_stock_threshold
    cost = item.purchase_price or 0
    retail = item.selling_price_retail or 0

    if stock == 0:
      status = "out_of_stock"
    elif threshold is not None and stock <= threshold:
      status = "low_stock"
    else:
      status = "in_stock"

    items_out.append({
      "id": item.id,
      "item_name": item.item_name,
      "brand_name": item.brand_name,
      "category": item.category or "Uncategorized",
      "current_stock": stock,
      "purchase_price": cost,
      "selling_price_retail": retail,
      "selling_price_wholesale": item.selling_price_wholesale or 0,
      "value_at_cost": round(stock * cost, 2),
      "value_at_retail": round(stock * retail, 2),
      "units_sold_30d": int(units_sold_30d),
      "low_stock_threshold": threshold,
      "unit": item.unit_of_measurement or "Pcs",
      "stock_status": status,
    })

  total_cost = sum(i["value_at_cost"] for i in items_out)
  total_retail = sum(i["value_at_retail"] for i in items_out)
  in_stock_list  = [i for i in items_out if i["stock_status"] == "in_stock"]
  low_list       = [i for i in items_out if i["stock_status"] == "low_stock"]
  out_list       = [i for i in items_out if i["stock_status"] == "out_of_stock"]
  dead_list      = [i for i in items_out if i["current_stock"] > 0 and i["units_sold_30d"] == 0]
  total_n        = len(items_out)
  health_pct     = round(len(in_stock_list) / total_n * 100) if total_n else 0

  # Group by category
  cat_map: Dict[str, Any] = {}
  for i in items_out:
    c = i["category"]
    if c not in cat_map:
      cat_map[c] = {"value_at_cost": 0.0, "item_count": 0, "units": 0}
    cat_map[c]["value_at_cost"] += i["value_at_cost"]
    cat_map[c]["item_count"]    += 1
    cat_map[c]["units"]         += i["current_stock"]
  by_category = sorted(
    [{"category": k, **v} for k, v in cat_map.items()],
    key=lambda x: x["value_at_cost"], reverse=True,
  )

  # Group by brand (top 15)
  brand_map: Dict[str, Any] = {}
  for i in items_out:
    b = i["brand_name"]
    if b not in brand_map:
      brand_map[b] = {"value_at_cost": 0.0, "item_count": 0}
    brand_map[b]["value_at_cost"] += i["value_at_cost"]
    brand_map[b]["item_count"]    += 1
  by_brand = sorted(
    [{"brand_name": k, **v} for k, v in brand_map.items()],
    key=lambda x: x["value_at_cost"], reverse=True,
  )[:15]

  return {
    "summary": {
      "total_value_at_cost":  round(total_cost, 2),
      "total_value_at_retail": round(total_retail, 2),
      "total_items":          total_n,
      "in_stock_count":       len(in_stock_list),
      "low_stock_count":      len(low_list),
      "out_of_stock_count":   len(out_list),
      "dead_stock_count":     len(dead_list),
      "stock_health_pct":     health_pct,
    },
    "by_category": by_category,
    "by_brand":    by_brand,
    "items": sorted(items_out, key=lambda x: x["value_at_cost"], reverse=True),
  }


# ── GST Summary Report ───────────────────────────────────────────────────────

class GstSlab(BaseModel):
  rate: float              # GST rate % (e.g. 5, 12, 18)
  invoice_count: int
  taxable_value: float     # sub_total (before tax)
  cgst: float              # half of total tax (intrastate assumption)
  sgst: float              # half of total tax (intrastate assumption)
  total_tax: float
  gross_billed: float      # grand_total (taxable + tax - discounts)

class GstSummaryResponse(BaseModel):
  from_date: str
  to_date: str
  slabs: List[GstSlab]
  totals: GstSlab

@router.get(
    "/gst-summary/",
    response_model=GstSummaryResponse,
    summary="GST liability summary by rate slab",
    description=(
        "Aggregates GST liability grouped by tax rate slab for the given date range.\n\n"
        "Each slab includes `taxable_value`, `cgst`, `sgst`, `total_tax`, and `gross_billed`.\n"
        "CGST and SGST are each assumed to be half of `total_tax` (intrastate assumption).\n\n"
        "Defaults: `from_date` = earliest invoice in DB; `to_date` = today."
    ),
    responses={400: {"description": "Invalid from_date or to_date — use YYYY-MM-DD"}},
)
def get_gst_summary(
  from_date: Optional[str] = Query(None, description="Start date YYYY-MM-DD (default: 365 days ago)"),
  to_date:   Optional[str] = Query(None, description="End date YYYY-MM-DD (default: today)"),
  db: Session = Depends(get_db),
):
  today = datetime.utcnow().date()

  if from_date:
    try:
      start = datetime.strptime(from_date, "%Y-%m-%d")
    except ValueError:
      raise HTTPException(status_code=400, detail="Invalid from_date. Use YYYY-MM-DD")
  else:
    # Default: earliest invoice in DB (so we show everything)
    earliest = db.query(func.min(InvoiceModel.invoice_date)).scalar()
    start = earliest if earliest else datetime(today.year, today.month, 1)

  if to_date:
    try:
      end = datetime.strptime(to_date, "%Y-%m-%d").replace(hour=23, minute=59, second=59)
    except ValueError:
      raise HTTPException(status_code=400, detail="Invalid to_date. Use YYYY-MM-DD")
  else:
    end = datetime.combine(today, datetime.max.time())

  rows = (
    db.query(
      InvoiceModel.tax_rate,
      func.count(InvoiceModel.id).label("invoice_count"),
      func.coalesce(func.sum(InvoiceModel.sub_total), 0).label("taxable_value"),
      func.coalesce(func.sum(InvoiceModel.total_tax_amount), 0).label("total_tax"),
      func.coalesce(func.sum(InvoiceModel.grand_total), 0).label("gross_billed"),
    )
    .filter(
      InvoiceModel.invoice_date >= start,
      InvoiceModel.invoice_date <= end,
    )
    .group_by(InvoiceModel.tax_rate)
    .order_by(InvoiceModel.tax_rate)
    .all()
  )

  slabs = []
  for r in rows:
    tax = round(float(r.total_tax), 2)
    slabs.append(GstSlab(
      rate=float(r.tax_rate or 0),
      invoice_count=int(r.invoice_count),
      taxable_value=round(float(r.taxable_value), 2),
      cgst=round(tax / 2, 2),
      sgst=round(tax / 2, 2),
      total_tax=tax,
      gross_billed=round(float(r.gross_billed), 2),
    ))

  totals = GstSlab(
    rate=0,
    invoice_count=sum(s.invoice_count for s in slabs),
    taxable_value=round(sum(s.taxable_value for s in slabs), 2),
    cgst=round(sum(s.cgst for s in slabs), 2),
    sgst=round(sum(s.sgst for s in slabs), 2),
    total_tax=round(sum(s.total_tax for s in slabs), 2),
    gross_billed=round(sum(s.gross_billed for s in slabs), 2),
  )

  return GstSummaryResponse(
    from_date=start.strftime("%Y-%m-%d"),
    to_date=end.strftime("%Y-%m-%d"),
    slabs=slabs,
    totals=totals,
  )


# ── Best Sellers Report ───────────────────────────────────────────────────────

def _period_cutoff(period: str) -> Optional[datetime]:
  if period == "7d":   return datetime.utcnow() - timedelta(days=7)
  if period == "30d":  return datetime.utcnow() - timedelta(days=30)
  if period == "90d":  return datetime.utcnow() - timedelta(days=90)
  return None  # "all"


def _base_line_items(db: Session, cutoff: Optional[datetime], customer_type: Optional[str]):
  """Return a query base over invoice_line_items filtered by date and optional customer type."""
  q = (
    db.query(InvoiceLineItemModel)
    .join(InvoiceModel, InvoiceLineItemModel.invoice_id == InvoiceModel.id)
  )
  if cutoff:
    q = q.filter(InvoiceModel.invoice_date >= cutoff)
  if customer_type:
    q = q.join(CustomerModel, InvoiceModel.customer_id == CustomerModel.id)
    q = q.filter(CustomerModel.customer_type == customer_type)
  return q


@router.get(
    "/best-sellers/",
    summary="Best sellers — items, brands, price brackets, segments",
    description=(
        "Multi-dimensional sales performance report.\n\n"
        "**Returns four sections:**\n"
        "- `items`: top N items ranked by `metric` (units or revenue)\n"
        "- `brands`: top 15 brands by revenue\n"
        "- `price_brackets`: sales distribution across 5 price ranges (₹0–100, 101–500, 501–1000, 1001–5000, 5000+)\n"
        "- `by_segment`: Retail vs Wholesale totals with top 5 items per segment\n\n"
        "**Params:** `period` (7d/30d/90d/all), `metric` (units/revenue), `limit` (5–50), `customer_type` (Retail/Wholesale filter)."
    ),
)
def get_best_sellers(
  period:        str           = Query("30d", pattern="^(7d|30d|90d|all)$"),
  metric:        str           = Query("units", pattern="^(units|revenue)$"),
  limit:         int           = Query(10, ge=5, le=50),
  customer_type: Optional[str] = None,
  db: Session = Depends(get_db),
):
  cutoff = _period_cutoff(period)
  today  = datetime.utcnow()

  # ── Top items ────────────────────────────────────────────────────────────────
  order_col = (
    func.sum(InvoiceLineItemModel.quantity * InvoiceLineItemModel.price)
    if metric == "revenue"
    else func.sum(InvoiceLineItemModel.quantity)
  )

  item_q = (
    db.query(
      InvoiceLineItemModel.item_id,
      ItemModel.item_name,
      ItemModel.brand_name,
      func.coalesce(ItemModel.category, 'Uncategorized').label('category'),
      func.sum(InvoiceLineItemModel.quantity).label('units_sold'),
      func.sum(InvoiceLineItemModel.quantity * InvoiceLineItemModel.price).label('revenue'),
      func.avg(InvoiceLineItemModel.price).label('avg_price'),
    )
    .join(ItemModel,    InvoiceLineItemModel.item_id    == ItemModel.id)
    .join(InvoiceModel, InvoiceLineItemModel.invoice_id == InvoiceModel.id)
    .filter(ItemModel.is_active == True)
  )
  if cutoff:
    item_q = item_q.filter(InvoiceModel.invoice_date >= cutoff)
  if customer_type:
    item_q = item_q.join(CustomerModel, InvoiceModel.customer_id == CustomerModel.id)
    item_q = item_q.filter(CustomerModel.customer_type == customer_type)

  item_rows = (
    item_q
    .group_by(InvoiceLineItemModel.item_id, ItemModel.item_name, ItemModel.brand_name, ItemModel.category)
    .order_by(order_col.desc())
    .limit(limit)
    .all()
  )

  items = [
    {
      "rank":      idx + 1,
      "item_id":   r.item_id,
      "item_name": r.item_name,
      "brand_name": r.brand_name,
      "category":  r.category,
      "units_sold": int(r.units_sold),
      "revenue":   round(float(r.revenue), 2),
      "avg_price": round(float(r.avg_price), 2),
    }
    for idx, r in enumerate(item_rows)
  ]

  # ── Brand performance ────────────────────────────────────────────────────────
  brand_q = (
    db.query(
      ItemModel.brand_name,
      func.sum(InvoiceLineItemModel.quantity).label('units_sold'),
      func.sum(InvoiceLineItemModel.quantity * InvoiceLineItemModel.price).label('revenue'),
      func.count(func.distinct(InvoiceLineItemModel.item_id)).label('item_count'),
    )
    .join(ItemModel,    InvoiceLineItemModel.item_id    == ItemModel.id)
    .join(InvoiceModel, InvoiceLineItemModel.invoice_id == InvoiceModel.id)
    .filter(ItemModel.is_active == True)
  )
  if cutoff:
    brand_q = brand_q.filter(InvoiceModel.invoice_date >= cutoff)
  if customer_type:
    brand_q = brand_q.join(CustomerModel, InvoiceModel.customer_id == CustomerModel.id)
    brand_q = brand_q.filter(CustomerModel.customer_type == customer_type)

  brand_rows = (
    brand_q
    .group_by(ItemModel.brand_name)
    .order_by(func.sum(InvoiceLineItemModel.quantity * InvoiceLineItemModel.price).desc())
    .limit(15)
    .all()
  )
  brands = [
    {
      "rank":       idx + 1,
      "brand_name": r.brand_name,
      "units_sold": int(r.units_sold),
      "revenue":    round(float(r.revenue), 2),
      "item_count": int(r.item_count),
    }
    for idx, r in enumerate(brand_rows)
  ]

  # ── Price brackets ───────────────────────────────────────────────────────────
  BRACKETS = [
    ("₹0–100",     0,    100),
    ("₹101–500",   101,  500),
    ("₹501–1000",  501,  1000),
    ("₹1001–5000", 1001, 5000),
    ("₹5000+",     5001, None),
  ]
  price_brackets = []
  for label, min_p, max_p in BRACKETS:
    bq = (
      db.query(
        func.coalesce(func.sum(InvoiceLineItemModel.quantity), 0).label('units'),
        func.coalesce(func.sum(InvoiceLineItemModel.quantity * InvoiceLineItemModel.price), 0).label('revenue'),
        func.count(func.distinct(InvoiceLineItemModel.item_id)).label('item_count'),
      )
      .join(InvoiceModel, InvoiceLineItemModel.invoice_id == InvoiceModel.id)
      .filter(InvoiceLineItemModel.price >= min_p)
    )
    if max_p is not None:
      bq = bq.filter(InvoiceLineItemModel.price <= max_p)
    if cutoff:
      bq = bq.filter(InvoiceModel.invoice_date >= cutoff)
    row = bq.one()
    price_brackets.append({
      "bracket":    label,
      "min_price":  min_p,
      "max_price":  max_p,
      "units_sold": int(row.units),
      "revenue":    round(float(row.revenue), 2),
      "item_count": int(row.item_count),
    })

  # ── Segment top items ────────────────────────────────────────────────────────
  def _segment_top(ctype: str, n: int = 5) -> List[Dict]:
    sq = (
      db.query(
        InvoiceLineItemModel.item_id,
        ItemModel.item_name,
        func.sum(InvoiceLineItemModel.quantity).label('units_sold'),
        func.sum(InvoiceLineItemModel.quantity * InvoiceLineItemModel.price).label('revenue'),
      )
      .join(ItemModel,    InvoiceLineItemModel.item_id    == ItemModel.id)
      .join(InvoiceModel, InvoiceLineItemModel.invoice_id == InvoiceModel.id)
      .join(CustomerModel, InvoiceModel.customer_id       == CustomerModel.id)
      .filter(ItemModel.is_active == True, CustomerModel.customer_type == ctype)
    )
    if cutoff:
      sq = sq.filter(InvoiceModel.invoice_date >= cutoff)
    rows = (
      sq.group_by(InvoiceLineItemModel.item_id, ItemModel.item_name)
      .order_by(func.sum(InvoiceLineItemModel.quantity).desc())
      .limit(n).all()
    )
    return [{"item_id": r.item_id, "item_name": r.item_name, "units_sold": int(r.units_sold), "revenue": round(float(r.revenue), 2)} for r in rows]

  def _segment_totals(ctype: str):
    tq = (
      db.query(
        func.coalesce(func.sum(InvoiceLineItemModel.quantity), 0).label('units'),
        func.coalesce(func.sum(InvoiceLineItemModel.quantity * InvoiceLineItemModel.price), 0).label('revenue'),
      )
      .join(InvoiceModel,  InvoiceLineItemModel.invoice_id == InvoiceModel.id)
      .join(CustomerModel, InvoiceModel.customer_id        == CustomerModel.id)
      .filter(CustomerModel.customer_type == ctype)
    )
    if cutoff:
      tq = tq.filter(InvoiceModel.invoice_date >= cutoff)
    return tq.one()

  rt = _segment_totals('Retail')
  wt = _segment_totals('Wholesale')

  by_segment = {
    "retail":    {"units_sold": int(rt.units), "revenue": round(float(rt.revenue), 2), "top_items": _segment_top('Retail')},
    "wholesale": {"units_sold": int(wt.units), "revenue": round(float(wt.revenue), 2), "top_items": _segment_top('Wholesale')},
  }

  return {
    "period":    period,
    "metric":    metric,
    "from_date": cutoff.strftime("%Y-%m-%d") if cutoff else None,
    "to_date":   today.strftime("%Y-%m-%d"),
    "items":     items,
    "brands":    brands,
    "price_brackets": price_brackets,
    "by_segment": by_segment,
  }
